# ansible-playbook -i inventory.yaml main.yaml --ask-become-pass --extra-vars="install_target=/dev/sdd"
- name: Generate the RPi5 Image and install to SD card
  import_playbook: playbooks/generate-img.yaml

- name: Tranfer SD card to RPi5 and wait for setup to finish
  hosts: rpi5
  gather_facts: no            ## it's not up yet, don't pull metrics
  tasks:
    - name: Wait for DietPi SSH access
      wait_for_connection:
        delay: 60             ## initial delay
        sleep: 20             ## check every
        connect_timeout: 8    ## try again after no response
        timeout: 500          ## max wait

    - name: Wait for DietPi global setup to complete
      wait_for:
        path: /boot/dietpi/.install_stage
        search_regex: 2                    ## indicates installation complete

- name: Configure Firewall, Desktop, and Touchpad
  import_playbook: playbooks/configure-rpi5.yaml

- name: Install the battery module
  import_playbook: playbooks/install-fakebattery.yaml

- name: Unlock the device
  import_playbook: playbooks/unlock-device.yaml

- name: Install Email Server
  import_playbook: playbooks/email-server.yaml
